---

version: "3.8"

services:

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    environment:
      - REDISTIMESERIES_ARGS="DUPLICATE_POLICY LAST"
    ports:
      - 6379:6379
      - 8001:8001

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=redis-explorer-app
    ports:
      - 3000:3000